# ==========================================================
# Copyright (c) 2026 COPYxMUSIC 
# All Rights Reserved. 
#
# Project      : COPYxMUSIC API Telegram Music Bot
# Powered By   : Copy
# Type         : API Based Telegram Music Bot
#
# Bot          : @COPYxMUSIC_BOT
# Channel      : https://t.me/CopymusicOfficial
# GitHub       : 
#
# Unauthorized copying, modification, or redistribution
# of this source code without permission is prohibited.
# ==========================================================
services:
  - type: worker
    name: COPYxMUSIC 
    runtime: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python -m COPYxMUSIC 
    plan: free
